#! /bin/tcsh -f

# This the main NetMHCstabpan 1.0 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2015 Sept 30	launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCstabpan 1.0 directory (mandatory)
setenv	NMHOME	/net/sund-nas.win.dtu.dk/storage/services/www/packages/netMHCstabpan/1.0/netMHCstabpan-1.0

# Specify path to NetMHCpan packages
set	NetMHCpan = /tools/src/netMHCpan-2.8/netMHCpan

# determine where to store temporary files (must be writable to all users)

if ( ${?TMPDIR} == 0 ) then
	setenv  TMPDIR  /tmp
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETMHCstabpan $NMHOME/$PLATFORM

# main ========================================================================
if ( -x $NETMHCstabpan/bin/netMHCstabpan ) then
   $NETMHCstabpan/bin/netMHCstabpan $* -affpred $NetMHCpan
else
   echo netMHCstabpan: no binaries found for $PLATFORM $NETMHCstabpan/bin/netMHCstabpan
endif

# end of script ===============================================================
